version: 0.0
os: linux
files: 
  - source: /
    destination: /home/ubuntu/deploy/lafu-server
hooks: 
    ApplicationStart:
        - location: scripts/application_start.sh
          timeout: 300
          runas: ubuntu